# copyright ############################### #
# This file is part of the Xtrack Package.  #
# Copyright (c) CERN, 2021.                 #
# ######################################### #

"""
Generate deterministic inverse-CDF tables for total synchrotron-radiation
energy loss.

The runtime ``quantum-efficient`` radiation mode does not need individual
photon energies. It only needs the total energy lost in a slice. For a fixed
number of emitted photons N, this script tabulates the distribution of

    X_N = x_1 + x_2 + ... + x_N,

where each ``x_i`` is an independent photon energy normalized by the critical
energy, ``x_i = E_i / E_c``. Tables are generated for powers of two,
``N = 1, 2, 4, ..., 256``.

The table generation is deterministic, not Monte Carlo:

1. The single-photon synchrotron spectrum ``S(x)`` is integrated to build a
   high-accuracy one-photon CDF. Near zero the integration uses ``x = y^3`` to
   remove the integrable ``x^(-2/3)`` singularity.
2. Multi-photon distributions are produced by repeated self-convolution in
   quantile/CDF space:
   CDF_2 = CDF_1 * CDF_1, CDF_4 = CDF_2 * CDF_2, and so on.
3. Each resulting CDF is inverted on a probability grid concentrated in both
   tails, currently down to ``TAIL_PROBABILITY_MIN``.
4. The generated C header stores ``log(X_N)`` quantiles, which improves
   interpolation in the low-energy tail where values span many orders of
   magnitude.

At runtime, after sampling the photon count from a Poisson distribution, the
count is decomposed into powers of two. For example, 312 photons are sampled as
``256 + 32 + 16 + 8``. One inverse-CDF table lookup is done for each chunk, and
the sampled chunk energies are summed. This replaces hundreds of individual
photon-energy samples with a few table lookups while preserving the total
energy-loss distribution up to the accuracy of the deterministic tables and
interpolation.
"""

from pathlib import Path

import numpy as np
from scipy.integrate import cumulative_trapezoid


POWERS = [1 << ii for ii in range(9)]

TAIL_PROBABILITY_MIN = 1e-15
TAIL_PROBABILITY_MAX = 1e-2
TAIL_POINTS_PER_DECADE = 160

# Offline generation tolerances. These affect generation/certification only,
# not the runtime table layout. TAIL_PROBABILITY_MIN already resolves the
# runtime inverse-CDF grid down to 1e-15; tightening it further should be driven
# by validation of tail observables, because it increases generated table size
# and therefore runtime cache pressure.
GEN_REL_TOL = 1e-12
GEN_ABS_TOL = 1e-15
TABLE_LOG_TOL = 1e-9

# All runtime tables are built with the same high-accuracy generation route.
# This avoids a handoff between methods and prevents small numerical drifts
# between low-count and high-count tables. Near zero, F_N(S) scales
# approximately as S^(N/3), so the higher-count tables are intrinsically
# smoother, but they are still generated by repeated certified convolution for
# consistency.
LOW_COUNT_SEED_POWERS = tuple(POWERS)
REFERENCE_TAIL_POINTS_PER_DECADE = 260
REFERENCE_CENTER_POINTS = 5001
CONVOLUTION_QUAD_TAIL_POINTS_PER_DECADE = 220
CONVOLUTION_QUAD_CENTER_POINTS = 4001
BINARY_SEARCH_ITERATIONS = 90

# Uniform grid used for convolution of normalized photon energies.
DX = 1e-4
X_MAX = 256.0

# Dense auxiliary grid near x=0 resolves the x^(-2/3) integrable singularity
# before the CDF is interpolated onto the uniform convolution grid.
N_LOW_GRID = 120_000
X_LOW_MAX = 1e-2


def synrad(x):
    """Evaluate the normalized single-photon synchrotron spectrum S(x)."""
    x = np.asarray(x)
    out = np.zeros_like(x, dtype=float)

    mask_low = (x > 0.0) & (x < 6.0)
    if np.any(mask_low):
        xx = x[mask_low]
        z = xx * xx / 16.0 - 2.0
        b = np.full_like(xx, 0.00000000000000000012)
        a = z * b + 0.00000000000000000460
        b = z * a - b + 0.00000000000000031738
        a = z * b - a + 0.00000000000002004426
        b = z * a - b + 0.00000000000111455474
        a = z * b - a + 0.00000000005407460944
        b = z * a - b + 0.00000000226722011790
        a = z * b - a + 0.00000008125130371644
        b = z * a - b + 0.00000245751373955212
        a = z * b - a + 0.00006181256113829740
        b = z * a - b + 0.00127066381953661690
        a = z * b - a + 0.02091216799114667278
        b = z * a - b + 0.26880346058164526514
        a = z * b - a + 2.61902183794862213818
        b = z * a - b + 18.65250896865416256398
        a = z * b - a + 92.95232665922707542088
        b = z * a - b + 308.15919413131586030542
        a = z * b - a + 644.86979658236221700714
        p = 0.5 * z * a - b + 414.56543648832546975110

        a = np.full_like(xx, 0.00000000000000000004)
        b = z * a + 0.00000000000000000289
        a = z * b - a + 0.00000000000000019786
        b = z * a - b + 0.00000000000001196168
        a = z * b - a + 0.00000000000063427729
        b = z * a - b + 0.00000000002923635681
        a = z * b - a + 0.00000000115951672806
        b = z * a - b + 0.00000003910314748244
        a = z * b - a + 0.00000110599584794379
        b = z * a - b + 0.00002581451439721298
        a = z * b - a + 0.00048768692916240683
        b = z * a - b + 0.00728456195503504923
        a = z * b - a + 0.08357935463720537773
        b = z * a - b + 0.71031361199218887514
        a = z * b - a + 4.26780261265492264837
        b = z * a - b + 17.05540785795221885751
        a = z * b - a + 41.83903486779678800040
        q = 0.5 * z * a - b + 28.41787374362784178164

        y = np.power(xx, 2.0 / 3.0)
        out[mask_low] = (
            p / y - q * y - 1.0) * 1.81379936423421784215530788143

    mask_high = (x >= 6.0) & (x < 800.0)
    if np.any(mask_high):
        xx = x[mask_high]
        z = 20.0 / xx - 2.0
        a = np.full_like(xx, 0.00000000000000000001)
        b = z * a - 0.00000000000000000002
        a = z * b - a + 0.00000000000000000006
        b = z * a - b - 0.00000000000000000020
        a = z * b - a + 0.00000000000000000066
        b = z * a - b - 0.00000000000000000216
        a = z * b - a + 0.00000000000000000721
        b = z * a - b - 0.00000000000000002443
        a = z * b - a + 0.00000000000000008441
        b = z * a - b - 0.00000000000000029752
        a = z * b - a + 0.00000000000000107116
        b = z * a - b - 0.00000000000000394564
        a = z * b - a + 0.00000000000001489474
        b = z * a - b - 0.00000000000005773537
        a = z * b - a + 0.00000000000023030657
        b = z * a - b - 0.00000000000094784973
        a = z * b - a + 0.00000000000403683207
        b = z * a - b - 0.00000000001785432348
        a = z * b - a + 0.00000000008235329314
        b = z * a - b - 0.00000000039817923621
        a = z * b - a + 0.00000000203088939238
        b = z * a - b - 0.00000001101482369622
        a = z * b - a + 0.00000006418902302372
        b = z * a - b - 0.00000040756144386809
        a = z * b - a + 0.00000287536465397527
        b = z * a - b - 0.00002321251614543524
        a = z * b - a + 0.00022505317277986004
        b = z * a - b - 0.00287636803664026799
        a = z * b - a + 0.06239591359332750793
        p = 0.5 * z * a - b + 1.06552390798340693166
        out[mask_high] = p * np.sqrt(0.5 * np.pi / xx) / np.exp(xx)

    return out


def make_probability_grid(tail_probability_min=TAIL_PROBABILITY_MIN,
                          tail_probability_max=TAIL_PROBABILITY_MAX,
                          tail_points_per_decade=TAIL_POINTS_PER_DECADE,
                          center_points=1601):
    """Build the inverse-CDF probability grid, with extra points in both tails."""
    n_tail = int(round(
        np.log10(tail_probability_max / tail_probability_min)
        * tail_points_per_decade))
    u_tail = np.logspace(
        np.log10(tail_probability_min),
        np.log10(tail_probability_max),
        n_tail,
    )
    u_center = np.linspace(
        tail_probability_max, 1 - tail_probability_max, center_points)
    return np.unique(np.concatenate((
        [0.0], u_tail, u_center, 1.0 - u_tail[::-1], [1.0])))


def make_reference_probability_grid():
    """Build a denser probability grid used only during offline generation."""
    return make_probability_grid(
        tail_points_per_decade=REFERENCE_TAIL_POINTS_PER_DECADE,
        center_points=REFERENCE_CENTER_POINTS)


def make_convolution_quadrature_grid():
    """Build the probability grid used to integrate self-convolutions."""
    return make_probability_grid(
        tail_points_per_decade=CONVOLUTION_QUAD_TAIL_POINTS_PER_DECADE,
        center_points=CONVOLUTION_QUAD_CENTER_POINTS)


def trapezoid_weights(x):
    """Return composite trapezoid weights for a sorted one-dimensional grid."""
    weights = np.empty_like(x)
    weights[0] = 0.5 * (x[1] - x[0])
    weights[-1] = 0.5 * (x[-1] - x[-2])
    weights[1:-1] = 0.5 * (x[2:] - x[:-2])
    return weights


def strictly_increasing(values):
    """Return a copy forced to be strictly increasing within roundoff."""
    out = np.array(values, dtype=float, copy=True)
    tiny = np.finfo(float).tiny
    for ii in range(1, out.size):
        if out[ii] <= out[ii - 1]:
            out[ii] = np.nextafter(max(out[ii - 1], tiny), np.inf)
    return out


def make_one_photon_cdf_grid():
    """Build a high-accuracy one-photon CDF grid.

    The low-energy region is integrated in the variable ``x = y^3``. This
    removes the integrable ``x^(-2/3)`` singularity from the quadrature problem
    before the CDF is inverted.
    """
    y_low = np.linspace(0.0, X_LOW_MAX ** (1.0 / 3.0), N_LOW_GRID)
    x_low = y_low**3

    # The rest of the domain is represented on a mixed log/linear grid. The
    # logarithmic part gives good resolution below the body of the spectrum;
    # the linear part keeps the high-energy tail monotonic and simple.
    x_mid = np.geomspace(X_LOW_MAX, 1.0, 120_000)
    x_high = np.linspace(1.0, X_MAX, 400_000)
    x_grid = np.unique(np.concatenate(([0.0], x_low, x_mid, x_high)))

    y_grid = synrad(x_grid)
    y_grid[0] = 0.0
    cdf_grid = cumulative_trapezoid(y_grid, x_grid, initial=0.0)

    norm = cdf_grid[-1]
    if not np.isfinite(norm) or norm <= 0.0:
        raise RuntimeError("Invalid one-photon CDF normalization")

    cdf_grid /= norm
    cdf_grid = np.maximum.accumulate(cdf_grid)
    cdf_grid[-1] = 1.0

    keep = np.concatenate(([True], np.diff(cdf_grid) > 0.0))
    return x_grid[keep], cdf_grid[keep]


def quantiles_from_cdf_grid(x_grid, cdf_grid, u_grid):
    """Invert a monotonic CDF grid onto a requested probability grid."""
    quantiles = np.interp(u_grid, cdf_grid, x_grid)
    if quantiles.size > 1:
        quantiles[0] = max(quantiles[1] * 0.1, np.finfo(float).tiny)
    return strictly_increasing(quantiles)


def cdf_from_quantiles(x, u_grid, quantiles):
    """Evaluate a CDF represented by a monotonic inverse-CDF table."""
    return np.interp(x, quantiles, u_grid, left=0.0, right=1.0)


def self_convolution_cdf(s_value, parent_u, parent_quantiles,
                         quadrature_u, quadrature_weights,
                         quadrature_quantiles):
    """Evaluate the CDF of the sum of two independent parent variables."""
    values = cdf_from_quantiles(
        s_value - quadrature_quantiles, parent_u, parent_quantiles)
    return np.sum(values * quadrature_weights)


def quantiles_from_self_convolution(parent_u, parent_quantiles, target_u,
                                    label):
    """Generate quantiles for the self-convolution of a parent distribution.

    The CDF is evaluated as ``int F_parent(s - Q_parent(u)) du`` and inverted
    by bisection. This is deliberately an offline method for low-count seed
    tables; it preserves a table-only runtime.
    """
    quadrature_u = make_convolution_quadrature_grid()
    quadrature_weights = trapezoid_weights(quadrature_u)
    quadrature_quantiles = np.interp(
        quadrature_u, parent_u, parent_quantiles)

    out = np.empty_like(target_u)
    out[0] = np.finfo(float).tiny
    out[-1] = X_MAX

    for ii in range(1, target_u.size - 1):
        probability = target_u[ii]
        lo = 0.0
        hi = X_MAX

        cdf_hi = self_convolution_cdf(
            hi, parent_u, parent_quantiles,
            quadrature_u, quadrature_weights, quadrature_quantiles)
        if cdf_hi < probability:
            out[ii] = X_MAX
            continue

        for _ in range(BINARY_SEARCH_ITERATIONS):
            mid = 0.5 * (lo + hi)
            cdf_mid = self_convolution_cdf(
                mid, parent_u, parent_quantiles,
                quadrature_u, quadrature_weights, quadrature_quantiles)
            if cdf_mid < probability:
                lo = mid
            else:
                hi = mid

            if hi - lo < max(GEN_ABS_TOL, GEN_REL_TOL * max(mid, 1.0)):
                break

        out[ii] = 0.5 * (lo + hi)

        if ii % 500 == 0:
            print(f"generated {label} quantile {ii}/{target_u.size}")

    if out.size > 1:
        out[0] = max(out[1] * 0.1, np.finfo(float).tiny)
    return strictly_increasing(out)


def certify_runtime_table(power, reference_u, reference_quantiles,
                          runtime_u, runtime_quantiles):
    """Report interpolation error introduced by the emitted runtime table.

    The reference quantiles are the high-accuracy offline distribution. The
    runtime quantiles are the compressed values that will be written to the C
    header. A ``CHECK`` here means the runtime probability grid/interpolation
    is not meeting ``TABLE_LOG_TOL``; it does not by itself mean the offline
    high-accuracy distribution construction failed.
    """
    audit_u = make_reference_probability_grid()
    q_reference = np.interp(audit_u, reference_u, reference_quantiles)
    log_reference = np.log(q_reference)
    log_runtime = np.interp(
        audit_u, runtime_u, np.log(runtime_quantiles))
    log_error = log_runtime - log_reference
    i_max = int(np.argmax(np.abs(log_error)))
    max_log_error = abs(log_error[i_max])

    status = "PASS" if max_log_error < TABLE_LOG_TOL else "CHECK"
    print(
        f"N={power:4d}"
        f" runtime-table max |dlogQ|={max_log_error:.6e}"
        f" limit={TABLE_LOG_TOL:.6e}"
        f" {status}"
        f" at u={audit_u[i_max]:.6e}"
        f" Q_ref={q_reference[i_max]:.6e}")
    return max_log_error


def build_total_energy_quantile_tables(u_grid=None):
    """Build all runtime total-energy inverse-CDF quantile tables.

    The one-photon table is generated from a high-accuracy CDF. Every higher
    power-of-two table is then generated by repeated deterministic
    self-convolution in quantile/CDF space. This is an offline-only cost; the
    returned tables have the same runtime format as the original generator.
    """
    if u_grid is None:
        u_grid = make_probability_grid()

    reference_u = make_reference_probability_grid()
    runtime_quantiles = {}

    print("building high-accuracy N=1 table")
    x1, cdf1 = make_one_photon_cdf_grid()
    q1_reference = quantiles_from_cdf_grid(x1, cdf1, reference_u)
    q1_runtime = np.interp(u_grid, reference_u, q1_reference)
    q1_runtime = strictly_increasing(q1_runtime)
    runtime_quantiles[1] = q1_runtime
    certify_runtime_table(1, reference_u, q1_reference, u_grid, q1_runtime)

    parent_reference = q1_reference
    for power in POWERS[1:]:
        print(f"building high-accuracy N={power} table")
        q_reference = quantiles_from_self_convolution(
            reference_u, parent_reference, reference_u, f"N={power}")
        q_runtime = strictly_increasing(np.interp(
            u_grid, reference_u, q_reference))
        runtime_quantiles[power] = q_runtime
        certify_runtime_table(
            power, reference_u, q_reference, u_grid, q_runtime)

        parent_reference = q_reference

    return u_grid, runtime_quantiles


def write_c_array(fid, name, values):
    """Write a one-dimensional double array in C header syntax."""
    fid.write(f"static const double {name}[XTRACK_SYNRAD_TOTAL_ENERGY_TABLE_SIZE] = {{\n")
    for ii in range(0, values.size, 4):
        chunk = values[ii:ii + 4]
        fid.write("    " + ", ".join(f"{vv:.17e}" for vv in chunk))
        if ii + 4 < values.size:
            fid.write(",")
        fid.write("\n")
    fid.write("};\n\n")


def main():
    """Generate all power-of-two inverse-CDF tables and write the C header."""
    out_path = Path(__file__).with_name("synrad_total_energy_tables.h")
    u_grid, quantile_tables = build_total_energy_quantile_tables()

    with out_path.open("w") as fid:
        fid.write("// copyright ############################### //\n")
        fid.write("// This file is part of the Xtrack Package.  //\n")
        fid.write("// Copyright (c) CERN, 2021.                 //\n")
        fid.write("// ######################################### //\n\n")
        fid.write("// Generated by xtrack/headers/_generate_synrad_total_energy_tables.py\n")
        fid.write("// Method: high-accuracy one-photon CDF followed by repeated\n")
        fid.write("// deterministic self-convolution in quantile/CDF space.\n")
        fid.write(f"// Convolution grid: DX = {DX}, X_MAX = {X_MAX}\n")
        fid.write(f"// Probability tails resolved down to {TAIL_PROBABILITY_MIN:.1e}.\n")
        fid.write("// Probability grid is concentrated in both tails; table values store\n")
        fid.write("// log(total normalized energy) for interpolation.\n\n")
        fid.write("#ifndef XTRACK_SYNRAD_TOTAL_ENERGY_TABLES_H\n")
        fid.write("#define XTRACK_SYNRAD_TOTAL_ENERGY_TABLES_H\n\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_TABLE_SIZE {u_grid.size}\n\n")

        write_c_array(fid, "synrad_total_energy_u_grid", u_grid)

        for power in POWERS:
            write_c_array(
                fid,
                f"synrad_total_energy_log_table_{power}",
                np.log(quantile_tables[power]),
            )

        fid.write("GPUFUN\n")
        fid.write("const double* synrad_get_total_energy_log_table_power2(int64_t nphot){\n")
        fid.write("    switch(nphot){\n")
        for power in POWERS:
            fid.write(
                f"        case {power}: return synrad_total_energy_log_table_{power};\n")
        fid.write("        default: return 0;\n")
        fid.write("    }\n")
        fid.write("}\n\n")
        fid.write("#endif /* XTRACK_SYNRAD_TOTAL_ENERGY_TABLES_H */\n")


if __name__ == "__main__":
    main()
